version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ./app:/server/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  qdrant_data:
